name: CI

on:
  pull_request:
    branches: [main]
    types: [synchronize, labeled]

jobs:
  label:
    if: (github.event.action=='labeled' && github.event.label.name=='pipeline-full') || (github.event.action!='labeled' && contains(github.event.pull_request.labels.*.name, 'pipeline-full'))
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Upload screenshots to argos-ci.com
        run: DEBUG=* npx @argos-ci/cli upload ./screenshots
